name: Depoly Function

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  depoly:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
    
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-cli@v1
        with:
          version: latest
      
      - run: supabase function depoly github-action-deploy --project-ref $PROJECT_ID